name: CI
on:
  release: 
    types: [published]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v4.1.1

      - name: Build
        run: |
          nimble install -d -y
          nimble buildr
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["*.exe"]'
